name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    name: Run tests in CI
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec --format doc
      - name: StandardRB Linter
        run: bundle exec standardrb --format github --parallel
